/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Digital;

/**
 *
 * @author Chou,Shu-Hung n7622236
 */
public class Switch extends javax.swing.JPanel {

    private OutputTerminal output=new OutputTerminal();
    /**
     * Creates new form Switch
     */
    public Switch() {
        initComponents();    
    }
    
    public Terminal getOutput(){
        return this.output;
    }
    /**
     * Set the value of output
     *
     * @param output new value of output
     */
    public void setOutput(OutputTerminal output) {
        this.output = output;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SwitchButton = new javax.swing.JToggleButton();

        SwitchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Digital/images/Switch_off.gif"))); // NOI18N
        SwitchButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        SwitchButton.setPreferredSize(new java.awt.Dimension(30, 35));
        SwitchButton.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Digital/images/Switch_on.gif"))); // NOI18N
        SwitchButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SwitchButtonStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SwitchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SwitchButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void SwitchButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SwitchButtonStateChanged
        output.setValue(SwitchButton.isSelected());
    }//GEN-LAST:event_SwitchButtonStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton SwitchButton;
    // End of variables declaration//GEN-END:variables
}
