/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package partg;

/**
 *
 * @author Chou,Shu-Hung n7622236@author Hung
 */
public class PartG extends javax.swing.JFrame {

    /**
     * Creates new form PartG
     */
    public PartG() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        circuitBoard1 = new Digital.CircuitBoard();
        switch1 = new Digital.Switch();
        bitAdderComponent1 = new Digital.BitAdderComponent();
        switch2 = new Digital.Switch();
        switch3 = new Digital.Switch();
        lED1 = new Digital.LED();
        lED2 = new Digital.LED();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        circuitBoard1.setLayout(null);
        circuitBoard1.add(switch1);
        switch1.setBounds(70, 90, 30, 35);

        bitAdderComponent1.setInput0(switch1.getOutput());
        bitAdderComponent1.setInput1(switch2.getOutput());
        bitAdderComponent1.setInput2(switch3.getOutput());

        javax.swing.GroupLayout bitAdderComponent1Layout = new javax.swing.GroupLayout(bitAdderComponent1);
        bitAdderComponent1.setLayout(bitAdderComponent1Layout);
        bitAdderComponent1Layout.setHorizontalGroup(
            bitAdderComponent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        bitAdderComponent1Layout.setVerticalGroup(
            bitAdderComponent1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );

        circuitBoard1.add(bitAdderComponent1);
        bitAdderComponent1.setBounds(210, 150, 48, 31);
        circuitBoard1.add(switch2);
        switch2.setBounds(70, 150, 30, 35);
        circuitBoard1.add(switch3);
        switch3.setBounds(70, 210, 30, 35);

        lED1.setInput(bitAdderComponent1.getOutput0());

        javax.swing.GroupLayout lED1Layout = new javax.swing.GroupLayout(lED1);
        lED1.setLayout(lED1Layout);
        lED1Layout.setHorizontalGroup(
            lED1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        lED1Layout.setVerticalGroup(
            lED1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        circuitBoard1.add(lED1);
        lED1.setBounds(340, 100, 30, 35);

        lED2.setInput(bitAdderComponent1.getOutput1());

        javax.swing.GroupLayout lED2Layout = new javax.swing.GroupLayout(lED2);
        lED2.setLayout(lED2Layout);
        lED2Layout.setHorizontalGroup(
            lED2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        lED2Layout.setVerticalGroup(
            lED2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        circuitBoard1.add(lED2);
        lED2.setBounds(340, 200, 30, 35);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(circuitBoard1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(circuitBoard1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PartG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PartG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PartG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PartG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PartG().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Digital.BitAdderComponent bitAdderComponent1;
    private Digital.CircuitBoard circuitBoard1;
    private Digital.LED lED1;
    private Digital.LED lED2;
    private Digital.Switch switch1;
    private Digital.Switch switch2;
    private Digital.Switch switch3;
    // End of variables declaration//GEN-END:variables
}
